- name: Custom Desktop tweeks
  hosts: kurron-desktop-tweaks 
  tasks:
      - name: Copy etc change script to a safe place
        copy: src=scripts/set-etc-environment.sh dest=/tmp/set-etc-environment.sh owner=root group=root mode=755 backup=no
      - name: Add silly environment variable
        command: /tmp/set-etc-environment.sh CUSTOM_RON_WAS_HERE true 
      - name: Copy Git configuration file
        copy: src=files/.gitconfig dest=/home/vagrant/.gitconfig owner=vagrant group=vagrant mode=644 backup=no
      - name: Copy bashrc change script to a safe place
        copy: src=scripts/append-line-to-bashrc.sh dest=/tmp/append-line-to-bashrc.sh owner=root group=root mode=755 backup=no
      - name: set editor to VI
        command: /tmp/append-line-to-bashrc.sh editor 'set -o vi' 
